routes/web.php
<?php

use App\Http\Controllers\BentukKontrakController;
use App\Http\Controllers\JenisKontrakController;
use App\Http\Controllers\KontrakController;
use App\Http\Controllers\PaketController;
use App\Http\Controllers\PenyediaController;
use App\Http\Controllers\PpkController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SatkerController;
use App\Http\Controllers\SppbjController;
use App\Http\Controllers\UndanganController;
use App\Http\Controllers\UnitKerjaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('satker', SatkerController::class);
    Route::resource('paket', PaketController::class);
    Route::resource('undangan', UndanganController::class);
    Route::resource('ppk', PpkController::class);
    Route::resource('penyedia', PenyediaController::class);
    Route::resource('unit-kerja', UnitKerjaController::class);
    Route::resource('sppbj', SppbjController::class);
    Route::resource('jenis-kontrak', JenisKontrakController::class);
    Route::resource('bentuk-kontrak', BentukKontrakController::class);
    Route::resource('kontrak', KontrakController::class);
    Route::get('kontrak/{kontrak}/download', [KontrakController::class, 'download'])->name('kontrak.download');
});

require __DIR__.'/auth.php';

app/Models/Penyedia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penyedia extends Model
{
    use HasFactory;

    public function kontrak()
    {
        return $this->hasMany(Kontrak::class);
    }

    public function sppbj()
    {
        return $this->hasMany(Sppbj::class);
    }
}

app/Http/Controllers/PenyediaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Penyedia;
use Illuminate\Http\Request;

class PenyediaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $penyedias = Penyedia::orderBy('nama_penyedia')->get();
        return view('penyedia.index', compact('penyedias'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('penyedia.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'nama_penyedia' => 'required',
            'nama_wakil_penyedia' => 'required',
            'jabatan_wakil_penyedia' => 'required',
            'bank' => 'required',
            'no_rek' => 'required',
            'npwp_penyedia' => 'required',
            'no_ktp_direktur' => 'required',
            'no_npwp_direktur' => 'required',
            'akta_pendirian' => 'required',
            'akta_perubahan' => 'required',
            'nib' => 'required',
            'alamat' => 'required',
        ]);

        $penyedia = new Penyedia;
        $penyedia->nama_penyedia = $validated['nama_penyedia'];
        $penyedia->nama_wakil_penyedia = $validated['nama_wakil_penyedia'];
        $penyedia->jabatan_wakil_penyedia = $validated['jabatan_wakil_penyedia'];
        $penyedia->bank = $validated['bank'];
        $penyedia->no_rek = $validated['no_rek'];
        $penyedia->npwp_penyedia = $validated['npwp_penyedia'];
        $penyedia->no_ktp_direktur = $validated['no_ktp_direktur'];
        $penyedia->no_npwp_direktur = $validated['no_npwp_direktur'];
        $penyedia->akta_pendirian = $validated['akta_pendirian'];
        $penyedia->akta_perubahan = $validated['akta_perubahan'];
        $penyedia->nib = $validated['nib'];
        $penyedia->alamat = $validated['alamat'];
        $penyedia->save();

        return redirect(route('penyedia.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Penyedia $penyedia)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Penyedia $penyedia)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Penyedia $penyedia)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Penyedia $penyedia)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/penyedia/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Penyedia') }}
        </h2>
    </x-slot>

    <div class="form-control w-full max-w-xs m-2">
        <form action="{{ route('penyedia.store') }}" method="post">
            @csrf
            <label class="label">
                <span class="label-text">Nama Penyedia</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2" name="nama_penyedia" />

            <label class="label">
                <span class="label-text">Nama Wakil Penyedia</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="nama_wakil_penyedia" />

            <label class="label">
                <span class="label-text">Jabatan Wakil Penyedia</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="jabatan_wakil_penyedia" />

            <label class="label">
                <span class="label-text">Bank</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="bank" />

            <label class="label">
                <span class="label-text">Nomor Rekening</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="no_rek" />

            <label class="label">
                <span class="label-text">NPWP Penyedia</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="npwp_penyedia" />

            <label class="label">
                <span class="label-text">Nomor KTP Direktur</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="no_ktp_direktur" />

            <label class="label">
                <span class="label-text">Nomor NPWP Direktur</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="no_npwp_direktur" />

            <label class="label">
                <span class="label-text">Akta Pendirian</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="akta_pendirian" />

            <label class="label">
                <span class="label-text">Akta Perubahan</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="akta_perubahan" />

            <label class="label">
                <span class="label-text">NIB</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="nib" />

            <label class="label">
                <span class="label-text">Alamat</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="alamat" />

            <button class="btn btn-outline btn-primary">Submit</button>
        </form>
    </div>
</x-app-layout>

resources/views/penyedia/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Penyedia') }}
        </h2>
        <a href="{{ route('penyedia.create') }}">
            <button class="btn btn-outline btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"
                    className="w-6 h-6" class="w-6 h-6 mr-1">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Tambah Penyedia
            </button>
        </a>
    </x-slot>

    <div class="overflow-x-auto">
        <table class="table table-zebra w-full">
            <!-- head -->
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nama Penyedia</th>
                    <th>Nama Wakil Penyedia</th>
                    <th>Jabatan Wakil Penyedia</th>
                    <th>Bank</th>
                    <th>Nomor Rekening</th>
                    <th>NPWP Penyedia</th>
                    <th>Nomor KTP Direktur</th>
                    <th>Nomor NPWP Direktur</th>
                    <th>Akta Pendirian</th>
                    <th>Akta Perubahan</th>
                    <th>NIB</th>
                    <th>Alamat</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($penyedias as $penyedia)
                <tr>
                    <th>{{ $loop->iteration }}</th>
                    <td>{{ $penyedia->nama_penyedia }}</td>
                    <td>{{ $penyedia->nama_wakil_penyedia }}</td>
                    <td>{{ $penyedia->jabatan_wakil_penyedia }}</td>
                    <td>{{ $penyedia->bank }}</td>
                    <td>{{ $penyedia->no_rek }}</td>
                    <td>{{ $penyedia->npwp_penyedia }}</td>
                    <td>{{ $penyedia->no_ktp_direktur }}</td>
                    <td>{{ $penyedia->no_npwp_direktur }}</td>
                    <td>{{ $penyedia->akta_pendirian }}</td>
                    <td>{{ $penyedia->akta_perubahan }}</td>
                    <td>{{ $penyedia->nib }}</td>
                    <td>{{ $penyedia->alamat }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-app-layout>