routes/web.php
<?php

use App\Http\Controllers\BentukKontrakController;
use App\Http\Controllers\JenisKontrakController;
use App\Http\Controllers\KontrakController;
use App\Http\Controllers\PaketController;
use App\Http\Controllers\PenyediaController;
use App\Http\Controllers\PpkController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SatkerController;
use App\Http\Controllers\SppbjController;
use App\Http\Controllers\UndanganController;
use App\Http\Controllers\UnitKerjaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('satker', SatkerController::class);
    Route::resource('paket', PaketController::class);
    Route::resource('undangan', UndanganController::class);
    Route::resource('ppk', PpkController::class);
    Route::resource('penyedia', PenyediaController::class);
    Route::resource('unit-kerja', UnitKerjaController::class);
    Route::resource('sppbj', SppbjController::class);
    Route::resource('jenis-kontrak', JenisKontrakController::class);
    Route::resource('bentuk-kontrak', BentukKontrakController::class);
    Route::resource('kontrak', KontrakController::class);
    Route::get('kontrak/{kontrak}/download', [KontrakController::class, 'download'])->name('kontrak.download');
});

require __DIR__.'/auth.php';

app/Models/Kontrak.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kontrak extends Model
{
    use HasFactory;

    public function bentukKontrak()
    {
        return $this->belongsTo(BentukKontrak::class);
    }
    public function jenisKontrak()
    {
        return $this->belongsTo(JenisKontrak::class);
    }
    public function ppk()
    {
        return $this->belongsTo(Ppk::class);
    }
    public function penyedia()
    {
        return $this->belongsTo(Penyedia::class);
    }
    public function sppbj()
    {
        return $this->belongsTo(Sppbj::class);
    }
}

app/Http/Controllers/KontrakController.php
<?php

namespace App\Http\Controllers;

use App\Models\BentukKontrak;
use App\Models\JenisKontrak;
use App\Models\Kontrak;
use App\Models\Penyedia;
use App\Models\Ppk;
use App\Models\Sppbj;
use Illuminate\Http\Request;
use PhpOffice\PhpWord\TemplateProcessor;

class KontrakController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kontraks = Kontrak::orderBy('no_kontrak')->get();
        return view('kontrak.index', compact('kontraks'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $sppbjs = Sppbj::orderBy('no_sppbj')->get();
        $ppks = Ppk::orderBy('nama_ppk')->get();
        $penyedias = Penyedia::orderBy('nama_penyedia')->get();
        $jenisKontraks = JenisKontrak::orderBy('jenis_kontrak')->get();
        $bentukKontraks = BentukKontrak::orderBy('bentuk_kontrak')->get();

        return view('kontrak.create', [
            'sppbjs' => $sppbjs,
            'ppks' => $ppks,
            'penyedias' => $penyedias,
            'jenisKontraks' => $jenisKontraks,
            'bentukKontraks' => $bentukKontraks,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'no_kontrak' => 'required',
            'sppbj_id' => 'required',
            'tanggal_kontrak' => 'required',
            'kota_kontrak' => 'required',
            'ppk_id' => 'required',
            'penyedia_id' => 'required',
            'jenis_kontrak_id' => 'required',
            'bentuk_kontrak_id' => 'required',
            'waktu_penyelesaian' => 'required',
            'tanggal_mulai' => 'required',
            'tanggal_selesai' => 'required',
            'file' => 'required',
            'status' => 'required',
            'keterangan' => 'required',
        ]);

        $kontrak = new Kontrak;
        $kontrak->no_kontrak = $validated['no_kontrak'];
        $kontrak->sppbj_id = $validated['sppbj_id'];
        $kontrak->tanggal_kontrak = $validated['tanggal_kontrak'];
        $kontrak->kota_kontrak = $validated['kota_kontrak'];
        $kontrak->ppk_id = $validated['ppk_id'];
        $kontrak->penyedia_id = $validated['penyedia_id'];
        $kontrak->jenis_kontrak_id = $validated['jenis_kontrak_id'];
        $kontrak->bentuk_kontrak_id = $validated['bentuk_kontrak_id'];
        $kontrak->waktu_penyelesaian = $validated['waktu_penyelesaian'];
        $kontrak->tanggal_mulai = $validated['tanggal_mulai'];
        $kontrak->tanggal_selesai = $validated['tanggal_selesai'];
        $kontrak->file = $validated['file'];
        $kontrak->status = $validated['status'];
        $kontrak->keterangan = $validated['keterangan'];
        $kontrak->save();

        return redirect(route('kontrak.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Kontrak $kontrak)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Kontrak $kontrak)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Kontrak $kontrak)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Kontrak $kontrak)
    {
        //
    }

    public function download(Kontrak $kontrak)
    {
        // $phpWord = new \PhpOffice\PhpWord\TemplateProcessor('kontrak-satu.docx');
        // $phpWord1 = new \PhpOffice\PhpWord\PhpWord();
        $templateProcessor = new TemplateProcessor('kontrak-satu.docx');

        $templateProcessor->setValues([
            'tanggal_mulai' => $kontrak->tanggal_mulai,
            'waktu_penyelesaian' => $kontrak->waktu_penyelesaian,
            'kota_kontrak' => $kontrak->kota_kontrak,
            'tanggal_kontrak' => $kontrak->tanggal_kontrak,
        ]);


        // Saving the document as HTML file...
        // $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord1, 'HTML');
        // $objWriter->save('template_kontrak.html');
        $templateProcessor->saveAs("Kontrak_$kontrak->no_kontrak.docx");

        return response()->download("Kontrak_$kontrak->no_kontrak.docx")->deleteFileAfterSend(true);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/kontrak/bentuk-kontrak.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Bentuk Kontrak') }}
        </h2>

        <a href="{{ route('kontrak.index') }}">
            <button class="btn btn-outline btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-5 h-5 m-1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
                </svg>
                Back
            </button>
        </a>
    </x-slot>
    <div class="p-5">
        <div class="form-control w-full max-w-xs m-2">
            <form action="{{ route('bentuk-kontrak.index') }}" method="post">
                @csrf
                <label class="label">
                    <span class="label-text">Bentuk Kontrak</span>
                </label>
                <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                    name="bentuk_kontrak" />
                <button class="btn btn-outline btn-primary">Submit</button>
            </form>
        </div>

        <div class="overflow-x-auto">
            <table class="table table-zebra w-full">
                <!-- head -->
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Bentuk Kontrak</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($bentukKontraks as $bentukKontrak)
                    <tr>
                        <th>{{ $loop->iteration }}</th>
                        <td>{{ $bentukKontrak->bentuk_kontrak }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>

resources/views/kontrak/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create Kontrak') }}
        </h2>
    </x-slot>

    <div class="form-control w-full max-w-xs m-2">
        <form action="{{ route('kontrak.store') }}" method="post">
            @csrf
            <label class="label">
                <span class="label-text">Nomor Kontrak</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="no_kontrak" />

            <label class="label">
                <span class="label-text">SPPBJ</span>
            </label>
            <select class="select select-bordered w-full max-w-xs" name="sppbj_id">
                <option disabled selected>Pilih SPPBJ</option>
                @foreach ($sppbjs as $sppbj)
                <option value="{{ $sppbj->id }}">{{ $sppbj->no_sppbj }}</option>
                @endforeach
            </select>

            <label class="label">
                <span class="label-text">Tanggal Kontrak</span>
            </label>
            <input type="date" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="tanggal_kontrak" />

            <label class="label">
                <span class="label-text">Kota Kontrak</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="kota_kontrak" />

            <label class="label">
                <span class="label-text">PPK</span>
            </label>
            <select class="select select-bordered w-full max-w-xs" name="ppk_id">
                <option disabled selected>Pilih PPK</option>
                @foreach ($ppks as $ppk)
                <option value="{{ $ppk->id }}">{{ $ppk->nama_ppk }}</option>
                @endforeach
            </select>

            <label class="label">
                <span class="label-text">Penyedia</span>
            </label>
            <select class="select select-bordered w-full max-w-xs" name="penyedia_id">
                <option disabled selected>Pilih Penyedia</option>
                @foreach ($penyedias as $penyedia)
                <option value="{{ $penyedia->id }}">{{ $penyedia->nama_penyedia }}</option>
                @endforeach
            </select>

            <label class="label">
                <span class="label-text">Jenis Kontrak</span>
            </label>
            <select class="select select-bordered w-full max-w-xs" name="jenis_kontrak_id">
                <option disabled selected>Pilih Jenis Kontrak</option>
                @foreach ($jenisKontraks as $jenisKontrak)
                <option value="{{ $jenisKontrak->id }}">{{ $jenisKontrak->jenis_kontrak }}</option>
                @endforeach
            </select>

            <label class="label">
                <span class="label-text">Bentuk Kontrak</span>
            </label>
            <select class="select select-bordered w-full max-w-xs" name="bentuk_kontrak_id">
                <option disabled selected>Pilih Bentuk Kontrak</option>
                @foreach ($bentukKontraks as $bentukKontrak)
                <option value="{{ $bentukKontrak->id }}">{{ $bentukKontrak->bentuk_kontrak }}</option>
                @endforeach
            </select>

            <label class="label">
                <span class="label-text">Waktu Penyelesaian</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="waktu_penyelesaian" />

            <label class="label">
                <span class="label-text">Tanggal Mulai</span>
            </label>
            <input type="date" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="tanggal_mulai" />

            <label class="label">
                <span class="label-text">Tanggal Selesai</span>
            </label>
            <input type="date" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="tanggal_selesai" />

            <label class="label">
                <span class="label-text">File</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="file" />
                
            <label class="label">
                <span class="label-text">Status</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="status" />

            <label class="label">
                <span class="label-text">Keterangan</span>
            </label>
            <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                name="keterangan" />
            
            <button class="btn btn-outline btn-primary">Submit</button>
        </form>
    </div>
</x-app-layout>

resources/views/kontrak/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Kontrak') }}
        </h2>

        <a href="{{ route('kontrak.create') }}">
            <button class="btn btn-outline btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5}
                    stroke="currentColor" className="w-6 h-6" class="w-6 h-6 mr-1">
                    <path strokeLinecap="round" strokeLinejoin="round"
                        d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Tambah Kontrak
            </button>
        </a>

        <a href="{{ route('bentuk-kontrak.index') }}">
            <button class="btn btn-outline btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5}
                    stroke="currentColor" className="w-6 h-6" class="w-6 h-6 mr-1">
                    <path strokeLinecap="round" strokeLinejoin="round"
                        d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Tambah Bentuk Kontrak
            </button>
        </a>

        <a href="{{ route('jenis-kontrak.index') }}">
            <button class="btn btn-outline btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5}
                    stroke="currentColor" className="w-6 h-6" class="w-6 h-6 mr-1">
                    <path strokeLinecap="round" strokeLinejoin="round"
                        d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Tambah Jenis Kontrak
            </button>
        </a>
    </x-slot>

    <div class="overflow-x-auto">
        <table class="table table-zebra w-full">
            <!-- head -->
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nomor Kontrak</th>
                    <th>SPPBJ</th>
                    <th>Tanggal Kontrak</th>
                    <th>Kota Kontrak</th>
                    <th>PPK</th>
                    <th>Penyedia</th>
                    <th>Jenis Kontrak</th>
                    <th>Bentuk Kontrak</th>
                    <th>Waktu Penyelesaian</th>
                    <th>Tanggal Mulai</th>
                    <th>Tanggal Selesai</th>
                    <th>Unit Kerja</th>
                    <th>File</th>
                    <th>Status</th>
                    <th>Keterangan</th>
                    <th>Download Kontrak</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($kontraks as $kontrak)
                <tr>
                    <th>{{ $loop->iteration }}</th>
                    <td>{{ $kontrak->no_kontrak }}</td>
                    <td>{{ $kontrak->sppbj->no_sppbj }}</td>
                    <td>{{ $kontrak->tanggal_kontrak }}</td>
                    <td>{{ $kontrak->kota_kontrak }}</td>
                    <td>{{ $kontrak->ppk->nama_ppk }}</td>
                    <td>{{ $kontrak->penyedia->nama_penyedia }}</td>
                    <td>{{ $kontrak->jenisKontrak->jenis_kontrak }}</td>
                    <td>{{ $kontrak->bentukKontrak->bentuk_kontrak }}</td>
                    <td>{{ $kontrak->waktu_penyelesaian }}</td>
                    <td>{{ $kontrak->tanggal_mulai }}</td>
                    <td>{{ $kontrak->tanggal_selesai }}</td>
                    <td>{{ $kontrak->sppbj->unitKerja->unit_kerja }}</td>
                    <td>{{ $kontrak->file }}</td>
                    <td>{{ $kontrak->status }}</td>
                    <td>{{ $kontrak->keterangan }}</td>
                    <td>
                        <a href="{{ route('kontrak.download', $kontrak->id) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                    d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                            </svg>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</x-app-layout>

resources/views/kontrak/jenis-kontrak.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Jenis Kontrak') }}
        </h2>

        <a href="{{ route('kontrak.index') }}">
            <button class="btn btn-outline btn-primary">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                    stroke="currentColor" class="w-5 h-5 m-1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3" />
                </svg>
                Back
            </button>
        </a>
    </x-slot>
    <div class="p-5">
        <div class="form-control w-full max-w-xs m-2">
            <form action="{{ route('jenis-kontrak.index') }}" method="post">
                @csrf
                <label class="label">
                    <span class="label-text">Jenis Kontrak</span>
                </label>
                <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                    name="jenis_kontrak" />
                <button class="btn btn-outline btn-primary">Submit</button>
            </form>
        </div>

        <div class="overflow-x-auto">
            <table class="table table-zebra w-full">
                <!-- head -->
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Jenis Kontrak</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($jenisKontraks as $jenisKontrak)
                    <tr>
                        <th>{{ $loop->iteration }}</th>
                        <td>{{ $jenisKontrak->jenis_kontrak }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>