routes/web.php
<?php

use App\Http\Controllers\BentukKontrakController;
use App\Http\Controllers\JenisKontrakController;
use App\Http\Controllers\KontrakController;
use App\Http\Controllers\PaketController;
use App\Http\Controllers\PenyediaController;
use App\Http\Controllers\PpkController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SatkerController;
use App\Http\Controllers\SppbjController;
use App\Http\Controllers\UndanganController;
use App\Http\Controllers\UnitKerjaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::resource('satker', SatkerController::class);
    Route::resource('paket', PaketController::class);
    Route::resource('undangan', UndanganController::class);
    Route::resource('ppk', PpkController::class);
    Route::resource('penyedia', PenyediaController::class);
    Route::resource('unit-kerja', UnitKerjaController::class);
    Route::resource('sppbj', SppbjController::class);
    Route::resource('jenis-kontrak', JenisKontrakController::class);
    Route::resource('bentuk-kontrak', BentukKontrakController::class);
    Route::resource('kontrak', KontrakController::class);
    Route::get('kontrak/{kontrak}/download', [KontrakController::class, 'download'])->name('kontrak.download');
});

require __DIR__.'/auth.php';

app/Models/UnitKerja.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UnitKerja extends Model
{
    use HasFactory;

    public function sppbj()
    {
        return $this->hasMany(Sppbj::class);
    }
}

app/Http/Controllers/UnitKerjaController.php
<?php

namespace App\Http\Controllers;

use App\Models\UnitKerja;
use Illuminate\Http\Request;

class UnitKerjaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $unitKerjas = UnitKerja::orderBy('unit_kerja')->get();
        return view('unit_kerja.index', compact('unitKerjas'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'unit_kerja' => 'required',
        ]);

        $unitKerja = new UnitKerja;
        $unitKerja->unit_kerja = $validated['unit_kerja'];
        $unitKerja->save();
        
        return redirect(route('unit-kerja.index'));
    }

    /**
     * Display the specified resource.
     */
    public function show(UnitKerja $unitKerja)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(UnitKerja $unitKerja)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, UnitKerja $unitKerja)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(UnitKerja $unitKerja)
    {
        //
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/unit_kerja/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Unit Kerja') }}
        </h2>
    </x-slot>
    <div class="p-5">
        <div class="form-control w-full max-w-xs m-2">
            <form action="{{ route('unit-kerja.store') }}" method="post">
                @csrf
                <label class="label">
                    <span class="label-text">Unit Kerja</span>
                </label>
                <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs mb-2"
                    name="unit_kerja" />
                <button class="btn btn-outline btn-primary">Submit</button>
            </form>
        </div>

        <div class="overflow-x-auto">
            <table class="table table-zebra w-full">
                <!-- head -->
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Unit Kerja</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($unitKerjas as $unitKerja)
                    <tr>
                        <th>{{ $loop->iteration }}</th>
                        <td>{{ $unitKerja->unit_kerja }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-app-layout>